SET DB_CLOSE_DELAY -1;
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1 RESTART WITH 3;
CREATE MEMORY TABLE "PUBLIC"."URL_ENTITIES"(

    "ID" BIGINT NOT NULL,

    "LONG_URL" CHARACTER VARYING(255)

);
CREATE MEMORY TABLE "PUBLIC"."STATS_UPDATE_HISTORY"(

    "ID" BIGINT NOT NULL

);
CREATE MEMORY TABLE "PUBLIC"."STATS"(

    "SHORT_URL" CHARACTER VARYING(255) NOT NULL,

    "COUNT" BIGINT,

    "LONG_URL" CHARACTER VARYING(255),

    "RANK" BIGINT,

    "ENTITY_ID" BIGINT NOT NULL

);
CREATE MEMORY TABLE "PUBLIC"."LOGS"(

    "ID" BIGINT NOT NULL,

    "QUERY_TIME" BIGINT,

    "ENTITY_ID" BIGINT NOT NULL

);
CREATE INDEX "PUBLIC"."IDXT6BY3AUCQRP5P17W0D6H5NQ5I" ON "PUBLIC"."STATS"("SHORT_URL" NULLS FIRST);
CREATE INDEX "PUBLIC"."IDXF0MKUDY21HBABFSXS50Y9NO8S" ON "PUBLIC"."URL_ENTITIES"("LONG_URL" NULLS FIRST);
ALTER TABLE "PUBLIC"."URL_ENTITIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");
ALTER TABLE "PUBLIC"."STATS_UPDATE_HISTORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");
ALTER TABLE "PUBLIC"."STATS" ADD CONSTRAINT "PUBLIC"."FK5P2QHPE1YLNJ1I3EPCMVJF6RQ" FOREIGN KEY("ENTITY_ID") REFERENCES "PUBLIC"."URL_ENTITIES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."STATS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("SHORT_URL");
ALTER TABLE "PUBLIC"."LOGS" ADD CONSTRAINT "PUBLIC"."FKXMTAW0WLGUX7RQTU5TAE48UQ" FOREIGN KEY("ENTITY_ID") REFERENCES "PUBLIC"."URL_ENTITIES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."LOGS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
